### ISSUE TITLE
CKEditor not visible in HelloWorld example

### ISSUE THREAD

**Issue by yishayw** [prominic/CKEditor-for-Royale#6]

**Comment by piotrzarzycki21** [comment]
This is the current state after latest changes for this example:

![result](https://user-images.githubusercontent.com/24554795/74921681-6c167180-53ce-11ea-821d-246720c5b283.gif)

Web Browser: Version 79.0.3945.130 (Official Build) (64-bit)

What's Init do ? Describe a bit better this button.

**Comment by piotrzarzycki21** [comment]
I'm available on skype to assist and help you to reach good state with that example.

**Comment by piotrzarzycki21** [comment]
Let's make also some clean up in case of all structures. Before it's happen we need to agree on some stuff. 
- I have on my PC folder **target** which contains stuff used to produce ckeditor.swc - typedefs 
Q1: Do we still need that to generate again typedefs ?
Q2: Do we miss anything to prepare that typedefs using build.xml ant build ? 
- It looks like we actually have here two swcs in play. Let's name them accordingly and place in libs folder. Proposition: `ckeditor-typedefs.swc`, `ckeditor.swc`
- We are going to have as part of this repository 3 types of items:
1. Stuff related to prepare `ckeditor-typedefs.swc`
2. Examples - currently only one called `HelloWorld`
3. Stuff related to prepare `ckeditor.swc` which is wrapper exposing some API
To **1** although I have prepared maven build it won't work cause we need some manual changes to the sources  - let's stay with ant build - unless you have an energy report stuff on dev list
To **3** I can try to prepare fully working Maven build 
To **2** we should have also Maven build and remove ant build script completely. Example should working also in Moonshine.

Proposition of folder structure for this repository:
```
Examples/HelloWorld
CKEditor/CKEditorTypeDefs/src
CKEditor/CKEditorTypeDefs/target - if needed
CKEditor/src
libs
```
Thoughts ?

**Comment by piotrzarzycki21** [comment]
> Proposition of folder structure for this repository:
> 
> ```
> Examples/HelloWorld
> CKEditor/CKEditorTypeDefs/src
> CKEditor/CKEditorTypeDefs/target - if needed
> CKEditor/src
> libs
> ```
> 
> Thoughts ?

@yishayw If you won't be able to provide those changes today - let me know by the end of the day. I will take care of that tomorrow morning. Additionally if there is anything above which we have talk about please comment here.

**Comment by yishayw** [comment]
```
> > Proposition of folder structure for this repository:
> > ```
> > Examples/HelloWorld
> > CKEditor/CKEditorTypeDefs/src
> > CKEditor/CKEditorTypeDefs/target - if needed
> > CKEditor/src
> > libs
> > ```
> > 
> > 
> > Thoughts ?
> 
> @yishayw If you won't be able to provide those changes today - let me know by the end of the day. I will take care of that tomorrow morning. Additionally if there is anything above which we have talk about please comment here.



I think the folder structure I committed should be ok. We still need to fix the build script.

**Comment by piotrzarzycki21** [comment]
Looking into your folder structure you are assuming that we don't need Wrapper CKEditor - I see only assumption that we have typedefs for build. - Could you distinguish that so I would not be confused by A: Stuff related to typedefs vs. B: Stuff related to wrapper - I thought we understand each other on a call.

**Comment by yishayw** [comment]
We need to add wrapper which is sibling of typedefs. I think CKEditor is redundant.

**Comment by piotrzarzycki21** [comment]
> We need to add wrapper which is sibling of typedefs. I think CKEditor is redundant.

Could you point me exact link where that wrapper currently is ?

**Comment by piotrzarzycki21** [comment]
> We still need to fix the build script.

Which of those 3 existing builds do you have in mind ? Unless you are referring to the one which I'm going to create. 
Build 1: https://github.com/prominic/CKEditor-for-Royale/blob/master/examples/HelloWorld/build.xml
Build 2: https://github.com/prominic/CKEditor-for-Royale/blob/master/examples/HelloWorld/build_example.xml
Build 3: https://github.com/prominic/CKEditor-for-Royale/blob/master/build.xml

**Comment by yishayw** [comment]
The one under typedefs

**Comment by yishayw** [comment]
I think the main one should run typedefs/build.xml and then wrapper/build.xml and then copy from targets to libs.

That's what I had in mind, but feel free to change this.

**Comment by piotrzarzycki21** [comment]
> I think the main one should run typedefs/build.xml and then wrapper/build.xml and then copy from targets to libs.
> 
> That's what I had in mind, but feel free to change this.

As I said the only Ant build which should be here is for typedefs, so wrapper will have Maven along with Examples. 

In the end I would like to have as always one command to build wrapper: `mvn clean package` and the same command to build example - nothing more. It looks like you have created different folder structure than my proposed, but it looks ok. 

I'm leaving you responsibility to handle typedefs ant build, rest of the builds will be maintained by GH actions.

**Comment by piotrzarzycki21** [comment]
Actually one thing worries me a bit from Moonshine project perspective. I would like to have 3 separated project, because Moonshine do not support modules. Since we have here 3 different cases it would looks like that:
1. Moonshine IDE file for HelloWorld place here -> https://github.com/prominic/CKEditor-for-Royale/tree/master/examples/HelloWorld
2. Moonshine IDE file for typedefs place here -> https://github.com/prominic/CKEditor-for-Royale/tree/master/typedefs
3. Moonshine IDE file for wrapper should be place - where ?

**Comment by piotrzarzycki21** [comment]
> I think the main one should run typedefs/build.xml and then wrapper/build.xml and then copy from targets to libs.

I prefer if that build prepare only typedefs swc nothing more - can you make sure that it happened ? It should build stuff to libs.

**Comment by yishayw** [comment]
I doubt there will be many changes in typedefs.swc, but we should make the build work. For now, we can just copy ckeditor.swc from libs as it is.

I think the wrapper library is likely to change more (unless we abandon ckeditor). It should just be compiled as a regular swc with, I'm guessing, an external dependency on typedefs.swc.

I suggest, if we still want to proceed with ckeditor, that for now you just replicate the HelloWorld example in MyAccount, with the wrapper in the src and ckeditor.swc in the lib.

Thoughts?

**Comment by piotrzarzycki21** [comment]
@yishayw Those two builds are the same ? 

1. https://github.com/prominic/CKEditor-for-Royale/blob/master/build.xml
2. https://github.com/prominic/CKEditor-for-Royale/blob/master/typedefs/build.xml

**Comment by yishayw** [comment]
https://github.com/prominic/CKEditor-for-Royale/issues/6#issuecomment-589093380

**Comment by piotrzarzycki21** [comment]
> I think the main one should run typedefs/build.xml and then wrapper/build.xml and then copy from targets to libs.
> 
> That's what I had in mind, but feel free to change this.

Damn! I missed it! Sorry for the noise!

**Comment by piotrzarzycki21** [comment]
So I can simply assume that this one -> https://github.com/prominic/CKEditor-for-Royale/blob/master/build.xml is the same as this one -> wrapper/build.xml ?

**Comment by yishayw** [comment]
Yes, for now I would concentrate on building the wrapper. ckeditor-typedefs.swc (should be renamed from ckeditor.swc) is unlikely to change in the near future. We just need to have both ckeditor-typedefs.wc and ckeditorwrapper.swc in libs so it can be used in other projects. That's how I see it now.
